// cli/templates/vue/src/components/ParameterControl.vue
<template>
  <div class="param-control">
    <label class="param-label">
      <span class="param-name">{{ schema.title || name }}</span>
      <span v-if="schema.description" class="param-description">{{ schema.description }}</span>
    </label>
    
    <!-- Yes/No Toggle -->
    <label v-if="isYesNoToggle" class="toggle-control">
      <input
        type="checkbox"
        :checked="value === 'yes'"
        @change="handleYesNoChange"
      />
      <span class="toggle-slider"></span>
      <span class="toggle-label">{{ value === 'yes' ? 'Yes' : 'No' }}</span>
    </label>

    <!-- Enum Dropdown -->
    <select
      v-else-if="schema.enum"
      :value="value"
      @change="handleChange"
      class="select-control"
    >
      <option v-for="option in schema.enum" :key="option" :value="option">
        {{ option }}
      </option>
    </select>

    <!-- Number Range (slider + input) -->
    <div
      v-else-if="isNumberRange"
      class="range-control"
    >
      <input
        type="range"
        :min="schema.minimum"
        :max="schema.maximum"
        :step="step"
        :value="value"
        @input="handleChange"
        class="range-slider"
      />
      <input
        type="number"
        :min="schema.minimum"
        :max="schema.maximum"
        :step="step"
        :value="value"
        @input="handleChange"
        class="range-input"
      />
    </div>

    <!-- Number Input -->
    <input
      v-else-if="schema.type === 'number' || schema.type === 'integer'"
      type="number"
      :step="step"
      :value="value"
      @input="handleChange"
      class="number-control"
    />

    <!-- Boolean Checkbox -->
    <label v-else-if="schema.type === 'boolean'" class="checkbox-control">
      <input
        type="checkbox"
        :checked="value"
        @change="handleChange"
      />
      <span class="checkbox-label">{{ value ? 'True' : 'False' }}</span>
    </label>

    <!-- Text Input -->
    <input
      v-else
      type="text"
      :value="value"
      @input="handleChange"
      class="text-control"
    />
  </div>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({
  name: String,
  schema: Object,
  value: [String, Number, Boolean],
});

const emit = defineEmits(['change']);

// Check if it's a yes/no toggle
const isYesNoToggle = computed(() => {
  return (
    props.schema.type === 'string' &&
    Array.isArray(props.schema.enum) &&
    props.schema.enum.length === 2 &&
    props.schema.enum.includes('yes') &&
    props.schema.enum.includes('no')
  );
});

// Check if it's a number range
const isNumberRange = computed(() => {
  return (
    (props.schema.type === 'number' || props.schema.type === 'integer') &&
    props.schema.minimum !== undefined &&
    props.schema.maximum !== undefined
  );
});

// Calculate step value
const step = computed(() => {
  return props.schema.multipleOf || (props.schema.type === 'integer' ? 1 : 0.1);
});

// Handle changes
const handleChange = (e) => {
  const { type, value: inputValue, checked } = e.target;

  if (type === 'checkbox' && props.schema.type === 'boolean') {
    emit('change', checked);
  } else if (type === 'number' || type === 'range') {
    const numValue = parseFloat(inputValue);
    if (props.schema.type === 'integer') {
      emit('change', Math.round(numValue));
    } else {
      emit('change', numValue);
    }
  } else {
    emit('change', inputValue);
  }
};

// Handle yes/no toggle
const handleYesNoChange = (e) => {
  emit('change', e.target.checked ? 'yes' : 'no');
};
</script>

// cli/templates/react/src/components/ParameterControl.jsx
/**
 * Parameter Control Component
 * @license GPL-3.0-or-later
 */

function ParameterControl({ name, schema, value, onChange }) {
  const handleChange = (e) => {
    const { type, value: inputValue, checked } = e.target;

    if (type === 'checkbox') {
      onChange(checked);
    } else if (type === 'number' || type === 'range') {
      const numValue = parseFloat(inputValue);
      if (schema.type === 'integer') {
        onChange(Math.round(numValue));
      } else {
        onChange(numValue);
      }
    } else {
      onChange(inputValue);
    }
  };

  // Render based on parameter type
  const renderControl = () => {
    // Boolean (yes/no toggle)
    if (
      schema.type === 'string' &&
      Array.isArray(schema.enum) &&
      schema.enum.length === 2 &&
      schema.enum.includes('yes') &&
      schema.enum.includes('no')
    ) {
      return (
        <label className="toggle-control">
          <input
            type="checkbox"
            checked={value === 'yes'}
            onChange={(e) => onChange(e.target.checked ? 'yes' : 'no')}
          />
          <span className="toggle-slider"></span>
          <span className="toggle-label">{value === 'yes' ? 'Yes' : 'No'}</span>
        </label>
      );
    }

    // Enum (dropdown)
    if (Array.isArray(schema.enum)) {
      return (
        <select value={value} onChange={handleChange} className="select-control">
          {schema.enum.map((option) => (
            <option key={option} value={option}>
              {option}
            </option>
          ))}
        </select>
      );
    }

    // Number with range (slider + input)
    if (
      (schema.type === 'number' || schema.type === 'integer') &&
      schema.minimum !== undefined &&
      schema.maximum !== undefined
    ) {
      const step = schema.multipleOf || (schema.type === 'integer' ? 1 : 0.1);
      
      return (
        <div className="range-control">
          <input
            type="range"
            min={schema.minimum}
            max={schema.maximum}
            step={step}
            value={value}
            onChange={handleChange}
            className="range-slider"
          />
          <input
            type="number"
            min={schema.minimum}
            max={schema.maximum}
            step={step}
            value={value}
            onChange={handleChange}
            className="range-input"
          />
        </div>
      );
    }

    // Number without range (plain input)
    if (schema.type === 'number' || schema.type === 'integer') {
      const step = schema.multipleOf || (schema.type === 'integer' ? 1 : 0.1);
      
      return (
        <input
          type="number"
          step={step}
          value={value}
          onChange={handleChange}
          className="number-control"
        />
      );
    }

    // Boolean (checkbox)
    if (schema.type === 'boolean') {
      return (
        <label className="checkbox-control">
          <input
            type="checkbox"
            checked={value}
            onChange={handleChange}
          />
          <span className="checkbox-label">{value ? 'True' : 'False'}</span>
        </label>
      );
    }

    // String (text input)
    return (
      <input
        type="text"
        value={value}
        onChange={handleChange}
        className="text-control"
      />
    );
  };

  return (
    <div className="param-control">
      <label className="param-label">
        <span className="param-name">{schema.title || name}</span>
        {schema.description && (
          <span className="param-description">{schema.description}</span>
        )}
      </label>
      {renderControl()}
    </div>
  );
}

export default ParameterControl;
