// cli/templates/svelte/src/lib/ParametersPanel.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import ParameterControl from './ParameterControl.svelte';

  export let schema;
  export let parameters;

  const dispatch = createEventDispatcher();

  let expandedGroups = {};

  // Get groups from schema
  $: groups = schema['x-groups'] || [
    { name: 'default', label: 'Parameters', parameters: Object.keys(schema.properties || {}) },
  ];

  // Toggle group expansion
  function toggleGroup(groupName) {
    expandedGroups = {
      ...expandedGroups,
      [groupName]: !expandedGroups[groupName],
    };
  }

  // Check if group is expanded (default to true)
  function isGroupExpanded(groupName) {
    return expandedGroups[groupName] !== false;
  }

  // Reset parameters to defaults
  function handleReset() {
    const defaults = {};
    for (const [key, prop] of Object.entries(schema.properties || {})) {
      defaults[key] = prop.default;
    }
    Object.entries(defaults).forEach(([key, value]) => {
      dispatch('change', { name: key, value });
    });
  }
</script>

<aside class="params-panel">
  <div class="params-header">
    <h2>Parameters</h2>
    <button on:click={handleReset} class="reset-button" title="Reset to defaults">
      ↺ Reset
    </button>
  </div>

  <div class="params-content">
    {#each groups as group (group.name)}
      <div class="param-group">
        <button
          class="group-header"
          on:click={() => toggleGroup(group.name)}
          aria-expanded={isGroupExpanded(group.name)}
        >
          <span class="group-icon">{isGroupExpanded(group.name) ? '▼' : '▶'}</span>
          <span class="group-label">{group.label || group.name}</span>
        </button>

        {#if isGroupExpanded(group.name)}
          <div class="group-content">
            {#each group.parameters as paramName (paramName)}
              {#if schema.properties[paramName]}
                <ParameterControl
                  name={paramName}
                  schema={schema.properties[paramName]}
                  value={parameters[paramName]}
                  on:change={(e) => dispatch('change', { name: paramName, value: e.detail })}
                />
              {/if}
            {/each}
          </div>
        {/if}
      </div>
    {/each}
  </div>
</aside>

// cli/templates/vue/src/components/ParametersPanel.vue
<template>
  <aside class="params-panel">
    <div class="params-header">
      <h2>Parameters</h2>
      <button @click="handleReset" class="reset-button" title="Reset to defaults">
        ↺ Reset
      </button>
    </div>

    <div class="params-content">
      <div v-for="group in groups" :key="group.name" class="param-group">
        <button
          class="group-header"
          @click="toggleGroup(group.name)"
          :aria-expanded="isGroupExpanded(group.name)"
        >
          <span class="group-icon">{{ isGroupExpanded(group.name) ? '▼' : '▶' }}</span>
          <span class="group-label">{{ group.label || group.name }}</span>
        </button>

        <div v-if="isGroupExpanded(group.name)" class="group-content">
          <ParameterControl
            v-for="paramName in group.parameters"
            :key="paramName"
            :name="paramName"
            :schema="schema.properties[paramName]"
            :value="parameters[paramName]"
            @change="(value) => $emit('change', paramName, value)"
          />
        </div>
      </div>
    </div>
  </aside>
</template>

<script setup>
import { ref, computed } from 'vue';
import ParameterControl from './ParameterControl.vue';

const props = defineProps({
  schema: Object,
  parameters: Object,
});

const emit = defineEmits(['change']);

const expandedGroups = ref({});

// Get groups from schema
const groups = computed(() => {
  return props.schema['x-groups'] || [
    { name: 'default', label: 'Parameters', parameters: Object.keys(props.schema.properties || {}) },
  ];
});

// Toggle group expansion
const toggleGroup = (groupName) => {
  expandedGroups.value = {
    ...expandedGroups.value,
    [groupName]: !expandedGroups.value[groupName],
  };
};

// Check if group is expanded (default to true)
const isGroupExpanded = (groupName) => {
  return expandedGroups.value[groupName] !== false;
};

// Reset parameters to defaults
const handleReset = () => {
  const defaults = {};
  for (const [key, prop] of Object.entries(props.schema.properties || {})) {
    defaults[key] = prop.default;
  }
  Object.entries(defaults).forEach(([key, value]) => {
    emit('change', key, value);
  });
};
</script>
